# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 456ce6a07687696297b76c2f3ce649611268ee29fe92a31d2e16cda22486a644baebe3ebf23620dc065e61263f7c980c9f099b5f76fb60f6d31c80a793d8b873

test:
  secret_key_base: ec1fc621278153400d7eefc9ad47ed17b8102ff45f05f141daea028663bb8675e5b6baa340c677e2fb93fe58d6ad1fa45bf31136ec740605f853eb134b5bc2f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
